### ISSUE TITLE
move this content into shadowbox project

### ISSUE THREAD

**Issue by jduncan-rva** [jduncan-rva/automated_workshops#3]
In an effort to streamline workflows, I'd like to move the ansible content from here and make it a part of https://github.com/RedHatGov/shadowbox

It wouldn't stop anything from working, of course, on any platform. 

Thoughts?

**Comment by jduncan-rva** [comment]
or just pull it in as a submodule.

**Comment by nzwulfin** [comment]
I've got no issues with moving it to live under shadowbox, but if you want to make it more available standalone to folks to use, it could make sense as a submodule.  Might be harder for folks to find / parse if they need to pull the site repo and then dig out the ansible content.

I don't work much with submodules, so I'm not sure how much of a burden that adds to maintaining the shadowbox site in Pelican.

**Comment by jduncan-rva** [comment]
I was thinking about making it a submodule too after mulling it over. I think that's the best path. I'll dig into it and act accordingly. This repo can stay unaffected.
